# Generated by Django 4.2.6 on 2023-10-06 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='articl_id',
            new_name='article_id',
        ),
    ]
